"""Global glossary and link map for cross-module consistency.

Aligned with v3.md section 3.4 L193-195.
"""
from typing import Any


def build_glossary(
    index_products: Any | None,
) -> dict[str, str]:
    """Build global glossary from public API symbols.

    Terms: exported class/function names
    Definitions: first sentence of docstring + kind + file location

    Returns: {term: definition} sorted by term.
    Returns empty dict when index_products is None or has no symbol_table.
    """
    if not index_products or not hasattr(index_products, "symbol_table"):
        return {}

    glossary: dict[str, str] = {}
    for sym in index_products.symbol_table.public_api():
        # First sentence of docstring
        doc_summary = ""
        if sym.docstring:
            first_sentence = sym.docstring.strip().split(".")[0]
            doc_summary = first_sentence.strip() + "."

        definition = f"{doc_summary} ({sym.kind.value}, {sym.file_path})".strip()
        glossary[sym.name] = definition

    return dict(sorted(glossary.items()))


def build_link_map(
    module_tree: dict,
) -> dict[str, str]:
    """Build stable link map for cross-module references.

    Keys are module path (stable, from tree["path"]).
    Values are document filenames generated by module_doc_filename()
    from codewiki/src/utils.py.

    Returns: {"src/auth": "Auth_Module.md", ...} sorted by key.
    """
    link_map: dict[str, str] = {}
    _walk_tree(module_tree, [], link_map)
    return dict(sorted(link_map.items()))


def _walk_tree(
    tree: dict,
    parent_path: list[str],
    link_map: dict[str, str],
) -> None:
    """Recursively walk module tree and populate link_map."""
    from codewiki.src.utils import module_doc_filename

    for title, info in tree.items():
        if not isinstance(info, dict):
            continue

        path = info.get("path", "")
        if path:
            # Use the stable path field (split into segments) as input to
            # module_doc_filename, NOT the title (which can drift with LLM naming).
            # module_doc_filename joins segments with "-" and normalizes chars.
            path_segments = parent_path + [path.replace("/", "_")]
            try:
                doc_filename = module_doc_filename(path_segments)
            except Exception:
                doc_filename = path.replace("/", "_") + ".md"
            link_map[path] = doc_filename

        children = info.get("children", {})
        if children and isinstance(children, dict):
            # Use path-derived segments for recursion, not title
            child_parent = parent_path + [path.replace("/", "_")] if path else parent_path
            _walk_tree(children, child_parent, link_map)
